/* Copyright (c) 2017 Kaluma
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef __MAGIC_STRINGS_H
#define __MAGIC_STRINGS_H

/* default */
#define MSTR_PROTOTYPE "prototype"
#define MSTR_REQUIRE "require"
#define MSTR_CREATE "create"

/* global */
#define MSTR_GLOBAL "global"
#define MSTR_HIGH "HIGH"
#define MSTR_LOW "LOW"
#define MSTR_INPUT "INPUT"
#define MSTR_OUTPUT "OUTPUT"
#define MSTR_INPUT_PULLUP "INPUT_PULLUP"
#define MSTR_INPUT_PULLDOWN "INPUT_PULLDOWN"
#define MSTR_LOW_LEVEL "LOW_LEVEL"
#define MSTR_HIGH_LEVEL "HIGH_LEVEL"
#define MSTR_RISING "RISING"
#define MSTR_FALLING "FALLING"
#define MSTR_CHANGE "CHANGE"
#define MSTR_PIN_MODE "pinMode"
#define MSTR_DIGITAL_READ "digitalRead"
#define MSTR_DIGITAL_WRITE "digitalWrite"
#define MSTR_DIGITAL_TOGGLE "digitalToggle"
#define MSTR_ATTACH_INTERRUPT "attachInterrupt"
#define MSTR_DETACH_INTERRUPT "detachInterrupt"
#define MSTR_ENABLE_INTERRUPTS "enableInterrupts"
#define MSTR_DISABLE_INTERRUPTS "disableInterrupts"
#define MSTR_PULSE_READ "pulseRead"
#define MSTR_TIMEOUT "timeout"
#define MSTR_START_STATE "startState"
#define MSTR_MODE "mode"
#define MSTR_TRIGGER "trigger"
#define MSTR_PIN "pin"
#define MSTR_EVENT "event"
#define MSTR_INTERVAL "interval"
#define MSTR_PULSE_WRITE "pulseWrite"
#define MSTR_SET_WATCH "setWatch"
#define MSTR_CLEAR_WATCH "clearWatch"
#define MSTR_ANALOG_READ "analogRead"
#define MSTR_ANALOG_WRITE "analogWrite"
#define MSTR_TONE "tone"
#define MSTR_NO_TONE "noTone"
#define MSTR_DURATION "duration"
#define MSTR_DUTY "duty"
#define MSTR_INVERSION "inversion"
#define MSTR_SET_TIMEOUT "setTimeout"
#define MSTR_SET_INTERVAL "setInterval"
#define MSTR_CLEAR_TIMEOUT "clearTimeout"
#define MSTR_CLEAR_INTERVAL "clearInterval"
#define MSTR_DELAY "delay"
#define MSTR_MILLIS "millis"
#define MSTR_DELAY_MICROSECONDS "delayMicroseconds"
#define MSTR_MICROS "micros"
#define MSTR_CONSOLE "console"
#define MSTR_LOG "log"
#define MSTR_ERROR "error"
#define MSTR_PRINT "print"
#define MSTR_SEED "seed"
#define MSTR_PROCESS "process"
#define MSTR_STDIN "stdin"
#define MSTR_STDOUT "stdout"
#define MSTR_ATOB "atob"
#define MSTR_BTOA "btoa"
#define MSTR_ENCODE_URI_COMPONENT "encodeURIComponent"
#define MSTR_DECODE_URI_COMPONENT "decodeURIComponent"
#define MSTR_ARCH "arch"
#define MSTR_PLATFORM "platform"
#define MSTR_VERSION "version"
#define MSTR_MEMORY_USAGE "memoryUsage"
#define MSTR_BINDING "binding"
#define MSTR_BUILTIN_MODULES "builtin_modules"
#define MSTR_GET_BUILTIN_MODULE "getBuiltinModule"
#define MSTR_DEVICES "devices"
#define MSTR_BOARD "board"
#define MSTR_UID "uid"
#define MSTR_NAME "name"
#define MSTR_PIN_NUM "PIN_NUM"
#define MSTR_LED_NUM "LED_NUM"
#define MSTR_BUTTON_NUM "BUTTON_NUM"
#define MSTR_PWM_NUM "PWM_NUM"
#define MSTR_ADC_NUM "ADC_NUM"
#define MSTR_I2C_NUM "I2C_NUM"
#define MSTR_SPI_NUM "SPI_NUM"
#define MSTR_UART_NUM "UART_NUM"
#define MSTR_LED "led"
#define MSTR_BUTTON "button"
#define MSTR_PWM "pwm"
#define MSTR_ADC "adc"
#define MSTR_ID "id"
#define MSTR_EXPORTS "exports"
#define MSTR_TEXT_ENCODER "TextEncoder"
#define MSTR_ENCODING "encoding"
#define MSTR_ENCODE "encode"
#define MSTR_TEXT_DECODER "TextDecoder"
#define MSTR_DECODE "decode"
#define MSTR_SYSTEM_ERROR "SystemError"
#define MSTR_ERRNO "errno"
#define MSTR_MESSAGE "message"
#define MSTR_ERROR_CLASS "Error"
#define MSTR_OBJECT "Object"
#define MSTR_CONSTRUCTOR "constructor"

/* device drivers: __netdev, __ieee80211dev */
#define MSTR___NETDEV "__netdev"
#define MSTR___IEEE80211dev "__ieee80211dev"
#define MSTR_FD "fd"
#define MSTR_PTCL "ptcl"
#define MSTR_STREAM "STREAM"
#define MSTR_DGRAM "DGRAM"
#define MSTR_STATE "state"
#define MSTR_LADDR "laddr"
#define MSTR_LPORT "lport"
#define MSTR_RADDR "raddr"
#define MSTR_RPORT "rport"
#define MSTR_CONNECT_CB "connect_cb"
#define MSTR_CLOSE_CB "close_cb"
#define MSTR_READ_CB "read_cb"
#define MSTR_ACCEPT_CB "accept_cb"
#define MSTR_SHUTDOWN_CB "shutdown_cb"
#define MSTR_MAC "mac"
#define MSTR_IP "ip"
#define MSTR_SOCKET "socket"
#define MSTR_DOMAIN "domain"
#define MSTR_PROTOCOL "protocol"
#define MSTR_GET "get"
#define MSTR_CONNECT "connect"
#define MSTR_ADDR "addr"
#define MSTR_PORT "port"
#define MSTR_CALLBACK "callback"
#define MSTR_WRITE "write"
#define MSTR_CLOSE "close"
#define MSTR_SHUTDOWN "shutdown"
#define MSTR_BIND "bind"
#define MSTR_LISTEN "listen"
#define MSTR_ASSOC_CB "assoc_cb"
#define MSTR_DISCONNECT_CB "disconnect_cb"
#define MSTR_RESET "reset"
#define MSTR_SCAN "scan"
#define MSTR_DISCONNECT "disconnect"
#define MSTR_GET_CONNECTION "get_connection"
#define MSTR_BSSID "bssid"
#define MSTR_SSID "ssid"
#define MSTR_SECURITY "security"
#define MSTR_RSSI "rssi"
#define MSTR_CHANNEL "channel"

#define MSTR_HEAP___STDIN "__stdin"
#define MSTR_HEAP___STDOUT "__stdout"
#define MSTR_HEAP_TOTAL "heapTotal"
#define MSTR_HEAP_PEAK "heapPeak"
#define MSTR_HEAP_USED "heapUsed"

#endif /* __MAGIC_STRINGS_H */
